apps:
  - name: kamihime-db
    script: build/index.js
    watch: true
    ignore_watch:
      - .git
      - build/proto
      - build/views
      - node_modules
      - provider
      - src
      - static
      - test
      - typings
    env:
      NODE_ENV: development
    env_production:
      NODE_ENV: production
