apps:
  - name: kamihime-db
    script: build/index.js
    watch:
      - build
    ignore_watch:
      - build/proto
      - build/views
    env:
      NODE_ENV: development
    env_production:
      NODE_ENV: production
