language: node_js
node_js:
  - 11
  - 10
sudo: false
before_install: cp src/auth/auth.example.ts src/auth/auth.ts
install: npm install
jobs:
  include:
    - stage: build
      script: npm run build
cache:
  directories:
    - node_modules
